name: XPU Verify

on:
  workflow_dispatch:

jobs:
  xpu_verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH and run XPU verify
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CLOUD_HOST }}
        username: ${{ secrets.CLOUD_USERNAME }}
        password: ${{ secrets.CLOUD_PASSWORD }}
        script: |
          rm -rf xpu_verify
          git clone https://github.com/rahulunair/xpu_verify
          cd xpu_verify
          ./xpu_verify.sh -c
      id: ssh
